import React from 'react';

let ship = [
    ['Country', 'ship'],
    ["North Korea", 967],
    ["China", 714],
    ["United States", 415],
    ["Iran", 398],
    ["Russia", 352],
    ["Egypt", 319],
    ["India", 295],
    ["Finland", 270],
    ["Colombia", 234],
    ["Indonesia", 221],
    ["Pakistan", 197],
    ["Turkey", 194],
    ["Bolivia", 173],
    ["South Korea", 166],
    ["Myanmar", 155],
    ["Italy", 143],
    ["Mexico", 143],
    ["Japan", 131],
    ["Morocco", 121],
    ["Philippines", 119],
    ["France", 118],
    ["Greece", 115],
    ["Brazil", 110],
    ["Denmark", 90],
    ["Bangladesh", 89],
    ["Taiwan", 87],
    ["Algeria", 85],
    ["Poland", 83],
    ["Thailand", 81],
    ["Germany", 81],
    ["Qatar", 80],
    ["United Kingdom", 76],
    ["United Arab Emirates", 75],
    ["Nigeria", 75],
    ["Chile", 69],
    ["Vietnam", 65],
    ["Israel", 65],
    ["Cameroon", 64],
    ["Canada", 63],
    ["Sweden", 63],
    ["Norway", 62],
    ["Malaysia", 61],
    ["Peru", 60],
    ["Iraq", 60],
    ["Honduras", 59],
    ["Angola", 57],
    ["Lebanon", 57],
    ["Syria", 56],
    ["Netherlands", 56],
    ["Saudi Arabia", 55],
    ["Tunisia", 50],
    ["Venezuela", 50],
    ["Romania", 48],
    ["Australia", 47],
    ["Spain", 46],
    ["Argentina", 42],
    ["Portugal", 41],
    ["Sri Lanka", 40],
    ["Singapore", 40],
    ["Paraguay", 40],
    ["Bahrain", 39],
    ["Albania", 38],
    ["Kuwait", 38],
    ["Jordan", 37],
    ["Laos", 36],
    ["Dominican Republic", 33],
    ["Azerbaijan", 31],
    ["Nicaragua", 30],
    ["South Africa", 30],
    ["Yemen", 30],
    ["Bulgaria", 29],
    ["Croatia", 28],
    ["Cambodia", 27],
    ["Guatemala", 26],
    ["Ukraine", 25],
    ["Democratic Republic of the Congo", 20],
    ["Uruguay", 20],
    ["Ghana", 20],
    ["Panama", 20],
    ["Serbia", 19],
    ["Ecuador", 19],
    ["Kenya", 19],
    ["Tanzania", 19],
    ["Montenegro", 18],
    ["Latvia", 18],
    ["Sudan", 18],
    ["Belgium", 17],
    ["Oman", 16],
    ["Kazakhstan", 15],
    ["Lithuania", 12],
    ["Cuba", 12],
    ["New Zealand", 11],
    ["Sierra Leone", 10],
    ["Ivory Coast", 10],
    ["Gabon", 10],
    ["Georgia", 9],
    ["Ireland", 8],
    ["Namibia", 8],
    ["Madagascar", 8],
    ["Uganda", 8],
    ["Mozambique", 8],
    ["Estonia", 6],
    ["Republic of the Congo", 6],
    ["Libya", 5],
    ["Mauritania", 5],
    ["El Salvador", 4],
    ["Turkmenistan", 4],
    ["Suriname", 3],
    ["Somalia", 3],
    ["Slovenia", 2],
    ["Macedonia", 0],
    ["Liberia", 0],
    ["Bosnia and Herzegovina", 0],
];
class Ship extends React.Component {
    state = {
        data: ship
    }
    render() {
        return (
            <div>
                <button className='btn-stat' onClick={() => {this.props.shipStatic(this.state.data)}}>Ship</button>
            </div>
        )
    }
}

export default Ship;